export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_BY_CODE = 'FETCH_COUNTRIES_BY_CODE';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const SELECT_REGION = 'SELECT_REGION';
export const HANDLE_SEARCH_ERROR = 'HANDLE_SEARCH_ERROR';
export const TOGGLE_DARKMODE = 'TOGGLE_DARKMODE';
